#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-guard-minitest
Version  : 2.4.4
Release  : 5
URL      : https://rubygems.org/downloads/guard-minitest-2.4.4.gem
Source0  : https://rubygems.org/downloads/guard-minitest-2.4.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rdoc

%description
# Guard::Minitest
[![Gem Version](https://badge.fury.io/rb/guard-minitest.png)](http://badge.fury.io/rb/guard-minitest) [![Build Status](https://travis-ci.org/guard/guard-minitest.png?branch=master)](https://travis-ci.org/guard/guard-minitest) [![Dependency Status](https://gemnasium.com/guard/guard-minitest.png)](https://gemnasium.com/guard/guard-minitest) [![Code Climate](https://codeclimate.com/github/guard/guard-minitest.png)](https://codeclimate.com/github/guard/guard-minitest) [![Coverage Status](https://coveralls.io/repos/guard/guard-minitest/badge.png?branch=master)](https://coveralls.io/r/guard/guard-minitest)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n guard-minitest-2.4.4
gem spec %{SOURCE0} -l --ruby > rubygem-guard-minitest.gemspec

%build
gem build rubygem-guard-minitest.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
guard-minitest-2.4.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/guard-minitest-2.4.4.gem
/usr/lib64/ruby/gems/2.3.0/gems/guard-minitest-2.4.4/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/guard-minitest-2.4.4/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/guard-minitest-2.4.4/README.md
/usr/lib64/ruby/gems/2.3.0/gems/guard-minitest-2.4.4/lib/guard/minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-minitest-2.4.4/lib/guard/minitest/inspector.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-minitest-2.4.4/lib/guard/minitest/notifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-minitest-2.4.4/lib/guard/minitest/reporter.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-minitest-2.4.4/lib/guard/minitest/reporters/old_reporter.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-minitest-2.4.4/lib/guard/minitest/runner.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-minitest-2.4.4/lib/guard/minitest/runners/old_runner.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-minitest-2.4.4/lib/guard/minitest/templates/Guardfile
/usr/lib64/ruby/gems/2.3.0/gems/guard-minitest-2.4.4/lib/guard/minitest/utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-minitest-2.4.4/lib/guard/minitest/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-minitest-2.4.4/lib/minitest/guard_minitest_plugin.rb
/usr/lib64/ruby/gems/2.3.0/specifications/guard-minitest-2.4.4.gemspec
